name: Build & Publish KoM Resource Pack (GitHub Pages)

on:
  push:
    branches: [ main ]  # executa sempre que fizer push na main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧱 Gera o ZIP do resource pack
      # Ajuste os paths conforme sua estrutura real (exemplo: pack.mcmeta + assets/)
      - name: Build resource pack ZIP
        run: |
          mkdir -p out
          zip -r "out/KoM-resource-pack.zip" assets pack.mcmeta

      # 📦 Envia o ZIP como artifact do GitHub Pages
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
